version: '3.1'

services:

  db:
    image: postgres
    restrat: always
    environment:
      - POSTGRES_PASSWORD: 123456
  adminer: 
    image: adminer
    restart: always
    ports: 
      -5432:5432